version: '3.5'
services:
  router-nginx:
    image: nginx:latest
    container_name: proxer-router-nginx
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - net
    # Перезапустит контейнер в непредвиденных ситуациях
    restart: unless-stopped
    # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - net
    profiles:
      - donotstart
    # Перезапустит контейнер в непредвиденных ситуациях
    restart: unless-stopped
    # Проверяет каждые 12 часов, нужны ли новые сертификаты
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  certbot-nginx:
    image: nginx:latest
    container_name: proxer-certbot-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/certbot-default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - net
    profiles:
      - donotstart
    restart: always
networks:
  net: