version: '3.5'
services:
  router:
    image: nginx:latest
    container_name: proxer-nginx
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
networks:
  net: